config/routes.rb
Rails.application.routes.draw do
  get 'event_comments/Index'
  get 'event_comments/New'
  get 'event_comments/Show'
  get 'place_comments/Index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :places
  resources :users
  resources :sessions
  resources :events
  resources :nearmes
  resources :profiles
  resources :nearmelists
  resources :categories
  resources :place_comments
  resources :event_comments
  resources :mailers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/event_comment.rb
class EventComment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :events
  has_many :place_comments
end

app/models/place_comment.rb
class PlaceComment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :place, optional: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user, only: [:new]

  #list all events
  def index
    @events = Event.where("end_time > ? ", Time.now)
  end

  def new
    @events = Event.all
    @places = Place.all
    @categories = Category.where(cat_type: 'Event')
  end

  #create event
  def create
    @event = Event.new(event_params)
    @event.user_id = session[:user_id]
    @event.enabled = 1
    @event.save
    redirect_to @event
  end

  #show single event
  def show
    @event = Event.find(params[:id])
    @event_comment = EventComment.new
    @event_comments = EventComment.order(id: :desc)
    @category = Category.find(@event.cat_id)
    @profiles = Profile.all
    @users = User.all
  end

  private
    def event_params
      params.require(:event).permit(:name, :place_id, :description, :start_time, :end_time, :cat_id)
    end
end

app/controllers/mailers_controller.rb
class MailersController < ApplicationController

  def create
    
  end
end

app/controllers/nearmes_controller.rb
class NearmesController < ApplicationController

  def index
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :require_user, only: [:new]
  #list all places
  def index
    @places = Place.all
  end

  def new
    @categories = Category.where(cat_type: 'Place')
  end

  #create place
  def create
    @place = Place.new(place_params)
    @place.save
    redirect_to @place
  end

  #show single
  def show
    @place_comment = PlaceComment.new
    # only last 5 EH
    @place_comments = PlaceComment.order(id: :desc).limit(6)
    @place = Place.find(params[:id])
    @category = Category.find(@place.cat_id)
    @profiles = Profile.all
    @users = User.all
  end

  private
    def place_params
      params.require(:place).permit(:name, :lat, :lng, :image_uri, :description, :cat_id, :address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_user, only: [:show]
  def index

  end

  def create
    @user = User.new(user_params)
    session[:user_id] = @user.id
    @user.role = 0
    @user.enabled = 1
    @user.save

    # Create a profile for user
    profile = Profile.new
    profile.image_uri = "https://i.stack.imgur.com/dr5qp.jpg"
    profile.user_id = @user.id
    profile.save

    UserMailer.welcome_email(@user).deliver_later(wait: 2.minutes)
    redirect_to(@user, :notice => 'User created')
    
    # flash[:success] = "Welcome to GNV Xplorer"
    redirect_to new_place_path

  end

  def show
    before_action :require_user, only: [:show]
    @user = User.find(params[:id])
    @users = User.all
  end

  def new
  end

  private
  def user_params
    params.require(:user).permit(:uname, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/event_comments_helper.rb
module EventCommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/place_comments_helper.rb
module PlaceCommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/index.html.erb
<div class="container">
  <div class="card text-center">
    <div class="card-header card-header-primary">
      <h1 class="text-center">Upcoming Events</h1>
    </div>
    <div class="card-body">
      <ul class="list-unstyled">
        <% @events.each do |event| %>
          <li class="media">
            <a href="<%=event_path(event)%>">
            <img class="mr-3" src="<%= Place.find(event.place_id).image_uri %>" alt="<%= Place.find(event.place_id).name %>"></a>
            <div class="media-body">
              <h5 class="mt-0 mb-1 text-left"><%= link_to event.name, event_path(event) %> @ <%=Place.find(event.place_id).name%> - <%=Place.find(event.place_id).address%></h5>
              <p class="text-left"><%=event.description%></p>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/events/new.html.erb
  <div class="container">
    <div class="card">
      <div class="card-body">
        <h3>Add New Event</h3>
        <%= form_with scope: :event, url: events_path, local: true do |form| %>
        <div class="input-group mb-3">
          <%= form.text_field :name, class: 'form-control', placeholder: :name, 'aria-label': :name, 'aria-describedby': 'basic-addon2', required: true %>
          <%= form.select :cat_id, options_from_collection_for_select(@categories, 'id', 'name', '1'), {}, {class: 'form-control', required: true } %>
        </div>
        <div class="input-group mb-3">
          <%= form.select :place_id, options_from_collection_for_select(@places, 'id', 'name', '1'), {}, {class: 'form-control', required: true } %>
        </div>
        <div class="input-group mb-3">
          <%= form.text_area :description, class: 'form-control', placeholder: :d, 'aria-label': :d, 'aria-describedby': 'basic-addon2', required: true %>
        </div>
        <%# http://daemonite.github.io/material/docs/4.1/material/pickers/#date-pickers %>
          <%# https://guides.rubyonrails.org/v2.3.11/form_helpers.html %>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <%= form.label :start %>
              </div>
              <%= form.datetime_select(:start_time,{ampm: true} ,{class: 'form-control' , required: true}) %>
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <%= form.label :end %>
              </div>
              <%= form.datetime_select(:end_time,{ampm: true} ,{class: 'form-control' , required: true}) %>
            </div>
            <div>
              <%= form.submit :submit, class:"btn btn-secondary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

app/views/events/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-body">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mb-3">
            <div class="card bg-dark text-white m-0">
              <img class="card-img">
              <img style="height:50vh;" src="<%= Place.find(@event.place_id).image_uri %>" alt="<%= Place.find(@event.place_id).image_uri %>">
              <div class="card-img-overlay">
                <h4 class="card-title">
                  <%=Place.find(@event.place_id).name %>
                </h4>
              </div>
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <div class="card bg-dark text-white m-0">
              <div id='map' class="places_map" data-place="<%= (Place.find(@event.place_id)).to_json %>" style="height:50vh;">
                <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.gmaps_api_key %>&callback=initMap"
                  type="text/javascript"></script>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-6 mb-3">
            <div class="card-body">
              <h4 class="card-title">
                <strong><%= @event.name %> @ <%= link_to Place.find(@event.place_id).name, place_path(@event.place_id) %> </strong> - <%= @category.name %>
                <i class="material-icons align-left">notifications</i>
              </h4>
              <h6 class="text-right">Added by <%=User.find(@event.user_id).uname %></h6>
              <hr>
              <p class="card-text">
                <%= @event.description %>
              </p>
              <br>
              <h6 class="card-subtitle mb-0 text-muted">Start Time</h6>
              <p class="card-text">
                <%=@event.start_time.strftime("%B %e, %Y at %I:%M %p") %>
              </p>
              <h6 class="card-subtitle mb-0 text-muted">End Time</h6>
              <p class="card-text">
                <%=@event.end_time.strftime("%B %e, %Y at %I:%M %p") %>
              </p>
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <div class="card-body">
              <h4 class="card-title"><strong>Comments</strong></h4>
              <hr>
              <% @event_comments.select{|e| e.event_id == @event.id}.each do |ec| %>
              <div class="media">
                <img class="align-self-start mr-3 img-circle img-fluid comment" src="<%= @profiles.find_by(user_id: ec.user_id).image_uri %>" alt="<%= @users.find_by(id:ec.user_id) %>">
                <div class="media-body">
                  <h5 class="mt-0 lead"><%= ec.title %></h5>
                  <p><%= ec.text %></p>
                </div>
              </div>
              <% end %>
              <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#commentModal">
                Add a Comment
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="commentModalTitle">Add a Comment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for @event_comment do |form| %>
          <%= hidden_field_tag :event_id, @event.id %>
            <div class="input-group mb-3">
              <%= form.text_field :title, class: 'form-control', placeholder: :title, 'aria-label': :title, 'aria-describedby': 'basic-addon2', required: true %>
            </div>
            <div class="input-group mb-3">
              <%= form.text_area :text, class: 'form-control', placeholder: 'Comment', 'aria-label': :text, 'aria-describedby': 'basic-addon2', required: true %>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= form.submit :submit, class:"btn btn-secondary" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/places/index.html.erb
  <div class="container">
    <div class="card text-center">
      <div class="card-header card-header-primary">
        <h1 class="text-center">All Places</h1>
      </div>
      <div class="card-body">
        <ul class="list-unstyled">
          <% @places.each do |place| %>
            <li class="media">
              <a href="<%=place_path(place)%>"><img class="mr-3 rounded" src="<%= place.image_uri %>" alt="<%= place.name %>"></a>
              <div class="media-body">
                <h5 class="mt-0 mb-1 text-left"><%= link_to place.name, place_path(place) %> - <%=place.address%> </h5>
                <p class="text-left"><%=place.description%></p>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

app/views/places/new.html.erb
  <div class="container">
    <div class="card">
      <div class="card-body">
        <h3>Add New Place</h3>
        <%= form_with scope: :place, url: places_path, local: true do |form| %>

        <div class="input-group mb-3">
          <%= form.text_field :name, class: 'form-control', placeholder: :name, 'aria-label': :name, 'aria-describedby': 'basic-addon2', required: true %>
          <%= form.select :cat_id, options_from_collection_for_select(@categories, 'id', 'name', '1'), {}, {class: 'form-control', required: true } %>
        </div>

        <div class="input-group mb-3">
          <%= form.select :googlename , {} , { prompt: 'Select After Entering Name' } , { class: 'form-control' } %>
        </div>

        <div class="input-group mb-3">
          <%= form.text_field :address, class: 'form-control', placeholder: "Address", 'aria-label': :name, 'aria-describedby': 'basic-addon2', required: true %>
        </div>
        <div class="input-group mb-3">
          <%= form.text_field :lat, class: 'form-control', placeholder: "Latitude", 'aria-label': :name, 'aria-describedby': 'basic-addon2', required: true %>
          <%= form.text_field :lng, class: 'form-control', placeholder: "Longitude", 'aria-label': :name, 'aria-describedby': 'basic-addon2', required: true %>
        </div>
        <div class="input-group mb-3">
          <%= form.text_field :image_uri, class: 'form-control', placeholder: "Image URL", 'aria-label': :name, 'aria-describedby': 'basic-addon2', required: true %>
        </div>
        <div class="input-group mb-3">
          <%= form.text_area :description, class: 'form-control', placeholder: :description, 'aria-label': :d, 'aria-describedby': 'basic-addon2', required: true %>
        </div>
        <div>
          <%= form.submit :submit, class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/places/show.html.erb
  <div class="container">
    <div class="card">
      <div class="card-body">
        <div class="container">
          <div class="row">
            <div class="col-md-6 mb-3">
              <div class="card bg-dark text-white m-0">
                <img class="card-img">
                <img style="height:50vh;" src="<%= @place.image_uri %>" alt="<%= @place.image_uri %>">
                <div class="card-img-overlay">
                  <h4 class="card-title">
                    <%=@place.name %>
                  </h4>
                </div>
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <div class="card bg-dark text-white m-0">
                <div id='map' class="places_map" data-place="<%= @place.to_json %>" style="height:50vh;">
                  <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.gmaps_api_key %>&callback=initMap"
                    type="text/javascript"></script>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mb-3">
              <div class="card-body">
                <h4 class="card-title">
                  <strong><%=@place.name %></strong> - <%= @category.name %>
                  <br>
                </h4>
                <h6><%=@place.address %></h6>
                <hr>
                <p class="card-text">
                  <%=@place.description %>
                </p>
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <div class="card-body">
                <h4 class="card-title"><strong>Comments</strong></h4>
                <hr>
                <% @place_comments.select{|p| p.place_id == @place.id}.each do |pc| %>
                <div class="media">
                  <img class="align-self-start mr-3 img-circle img-fluid comment" src="<%= @profiles.find_by(user_id: pc.user_id).image_uri %>" alt="<%= @users.find_by(id:pc.user_id) %>">
                  <div class="media-body">
                    <h5 class="mt-0 lead"><%= pc.title %></h5>
                    <p><%= pc.text %></p>
                  </div>
                </div>
                <% end %>
                <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#commentModal">
                  Add a Comment
                </button>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="commentModalTitle">Add a Comment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for @place_comment do |form| %>
          <%= hidden_field_tag :place_id, @place.id %>
            <div class="input-group mb-3">
              <%= form.text_field :title, class: 'form-control', placeholder: :title, 'aria-label': :title, 'aria-describedby': 'basic-addon2', required: true %>
            </div>
            <div class="input-group mb-3">
              <%= form.text_area :text, class: 'form-control', placeholder: 'Comment', 'aria-label': :text, 'aria-describedby': 'basic-addon2', required: true %>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= form.submit :submit, class:"btn btn-secondary" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
  <div class="container">
    <div class="card text-center">
      <div class="card-header card-header-primary">
        <h1 class="text-center">Sign Up Page</h1>
      </div>
      <div class="card-body">
        <%= form_with scope: :user, url: users_path, local: true do |form| %>

        <div class="input-group mb-3">
          <%= form.text_field :uname, class: 'form-control', placeholder: "Username", 'aria-label': :name, 'aria-describedby': 'basic-addon2', required: true %>
        </div>

        <div class="input-group mb-3">
          <%= form.password_field :password, class: 'form-control', placeholder: "Password", 'aria-label': :name, 'aria-describedby': 'basic-addon2', required: true %>
        </div>

        <div class="input-group mb-3">
          <%= form.text_field :email, class: 'form-control', placeholder: "Email Address", 'aria-label': :name, 'aria-describedby': 'basic-addon2', required: true %>
        </div>

        <div>
          <%= form.submit :"Create Account", class:"btn btn-secondary" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
  <h1>Listing Users</h1>

  <table>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.uname %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </table>

  <p>
    <strong>Username:</strong>
    <%= @user.uname %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

////


if params[:username] && params[:password]
   user = User.find_email(params[:email])
   return redirect_to sign_in_path unless user
   session[:user_id] = user.id if user.password == params[:password]

   @current_user = User.find(session[:user_id]) id session[:user_id]