config/routes.rb
Rails.application.routes.draw do
  get 'event_comments/Index'
  get 'event_comments/New'
  get 'event_comments/Show'
  get 'place_comments/Index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :places
  resources :users
  resources :sessions
  resources :events
  resources :nearmes
  resources :profiles
  resources :nearmelists
  resources :categories
  resources :place_comments
  resources :event_comments
  resources :mailers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/event_comment.rb
class EventComment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :events
  has_many :place_comments
end

app/models/place_comment.rb
class PlaceComment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :place, optional: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.name = params[:category][:name]
    @category.cat_type = params[:category][:cat_type]
    @category.description = params[:category][:description]
    @category.save

    flash[:success] = @category.name + " has been updated"
    redirect_to action: "index"
  end

  def edit
    @category = Category.find(params[:id])
    puts @category.cat_type
  end

  def create
    @category = Category.new(user_params)
    @category.enabled = 1
    @category.save

    flash[:success] = @category.name + " has been added"
    redirect_to action: "index"
  end

  def new
    @category = Category.new
  end  

  private
  def user_params
    params.require(:category).permit(:name, :cat_type, :description)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user, only: [:new]

  #list all events
  def index
    @events = Event.where("end_time > ? ", Time.now)
  end

  def new
    @events = Event.all
    @places = Place.all
    @categories = Category.where(cat_type: 'Event')
  end

  #create event
  def create
    @event = Event.new(event_params)
    @event.user_id = session[:user_id]
    @event.enabled = 1
    @event.save
    redirect_to @event
  end

  #show single event
  def show
    @event = Event.find(params[:id])
    @event_comment = EventComment.new
    @event_comments = EventComment.order(id: :desc)
    @category = Category.find(@event.cat_id)
    @profiles = Profile.all
    @users = User.all
  end

  private
    def event_params
      params.require(:event).permit(:name, :place_id, :description, :start_time, :end_time, :cat_id)
    end
end

app/controllers/mailers_controller.rb
class MailersController < ApplicationController

  def create
    
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :require_user, only: [:new]
  #list all places
  def index
    @places = Place.all
  end

  def new
    @categories = Category.where(cat_type: 'Place')
  end

  #create place
  def create
    @place = Place.new(place_params)
    @place.save
    redirect_to @place
  end

  #show single
  def show
    @place_comment = PlaceComment.new
    # only last 5 EH
    @place_comments = PlaceComment.order(id: :desc).limit(6)
    @place = Place.find(params[:id])
    @category = Category.find(@place.cat_id)
    @profiles = Profile.all
    @users = User.all
  end

  private
    def place_params
      params.require(:place).permit(:name, :lat, :lng, :image_uri, :description, :cat_id, :address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_user, only: [:show]
  def index

  end

  def create
    @user = User.new(user_params)
    session[:user_id] = @user.id
    @user.role = 0
    @user.enabled = 1
    @user.save

    # Create a profile for user
    profile = Profile.new
    profile.image_uri = "https://i.stack.imgur.com/dr5qp.jpg"
    profile.user_id = @user.id
    profile.save

    UserMailer.welcome_email(@user).deliver_later(wait: 2.minutes)
    redirect_to(@user, :notice => 'User created')
    
    # flash[:success] = "Welcome to GNV Xplorer"
    redirect_to new_place_path

  end

  def show
    before_action :require_user, only: [:show]
    @user = User.find(params[:id])
    @users = User.all
  end

  def new
  end

  private
  def user_params
    params.require(:user).permit(:uname, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/event_comments_helper.rb
module EventCommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/place_comments_helper.rb
module PlaceCommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
      <%= form_for category do |form| %>
        <div class="input-group mb-3"> 
          <%= form.text_field :name, class: 'form-control', placeholder: :name, 'aria-label': :name, 'aria-describedby': 'basic-addon2', required: true %>
          <% # TODO Leaving this for now does not autoselect on edit - EH %>
          <%= form.select :cat_type, options_for_select([['Select Type'], ['Place'], ['Event']], disabled: 'Select Type'), {}, {class: 'form-control', required: true } %>

        </div>
        <div class="input-group mb-3"> 
          <%= form.text_area :description, class: 'form-control', placeholder: :description, 'aria-label': :description, 'aria-describedby': 'basic-addon2', required: true %>
        </div>
          <%= form.submit :submit, class:"btn btn-secondary" %>
        </div>
      <% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class="card">
    <div class="card-body">
      <h3>Edit Category</h3>
      <%= render 'form', category: @category %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="card">
    <div class="card-header card-header-primary">
      <h1 class="text-center">Categories</h1>
    </div>
    <div class="accordion" id="accordionCategories">
      <% @categories.each do |category| %>
        <div class="card">
          <div class="card-header" id='heading<%= category.id %>'>
            <h5 class="mb-0">
              <button class="btn btn-link" type="button" data-toggle="collapse" data-target='#collapse<%= category.id %>' aria-expanded="true" aria-controls='#collapse<%= category.id %>'>
                <%= category.name %> - <%= category.cat_type %> 
              </button>
            </h5>
          </div>
          <div id='collapse<%= category.id %>' class="collapse" aria-labelledby='heading<%= category.id %>' data-parent="#accordionCategories">
            <div class="card-body">
              <%= category.description %>
              <%= link_to 'Edit', edit_category_path(category.id), { :class=>"btn btn-primary", :role=>"button" }  %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="card">
    <div class="card-body">
      <h3>Add New Category</h3>
        <%= render 'form', category: @category %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-header card-header-primary">
      <p><strong>Name: </strong><%= @category.name %></p>
      <p><strong>Type: </strong><%= @category.cat_type %></p>
      <p><strong>Description: </strong><%= @category.description %><p>

      <%= link_to 'Edit', edit_category_path(@category.id), { :class=>"btn btn-primary", :role=>"button" }  %>
    </div>
  </div>
</div>