config/routes.rb
Rails.application.routes.draw do
  get 'event_comments/Index'
  get 'event_comments/New'
  get 'event_comments/Show'
  get 'place_comments/Index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :places
  resources :users
  resources :sessions
  resources :events
  resources :nearmes
  resources :profiles
  resources :nearmelists
  resources :categories
  resources :place_comments
  resources :event_comments
  resources :mailers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/event_comment.rb
class EventComment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :events
  has_many :place_comments
end

app/models/place_comment.rb
class PlaceComment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :place, optional: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user, only: [:new]

  #list all events
  def index
    @events = Event.where("end_time > ? ", Time.now)
  end

  def new
    @events = Event.all
    @places = Place.all
    @categories = Category.where(cat_type: 'Event')
  end

  #create event
  def create
    @event = Event.new(event_params)
    @event.user_id = session[:user_id]
    @event.enabled = 1
    @event.save
    redirect_to @event
  end

  #show single event
  def show
    @event = Event.find(params[:id])
    @event_comment = EventComment.new
    @event_comments = EventComment.order(id: :desc)
    @category = Category.find(@event.cat_id)
    @profiles = Profile.all
    @users = User.all
  end

  private
    def event_params
      params.require(:event).permit(:name, :place_id, :description, :start_time, :end_time, :cat_id)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :require_user, only: [:new]
  #list all places
  def index
    @places = Place.all
  end

  def new
    @categories = Category.where(cat_type: 'Place')
  end

  #create place
  def create
    @place = Place.new(place_params)
    @place.save
    redirect_to @place
  end

  #show single
  def show
    @place_comment = PlaceComment.new
    # only last 5 EH
    @place_comments = PlaceComment.order(id: :desc).limit(6)
    @place = Place.find(params[:id])
    @category = Category.find(@place.cat_id)
    @profiles = Profile.all
    @users = User.all
  end

  private
    def place_params
      params.require(:place).permit(:name, :lat, :lng, :image_uri, :description, :cat_id, :address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_user, only: [:show]
  def index

  end

  def create
    @user = User.new(user_params)
    session[:user_id] = @user.id
    @user.role = 0
    @user.enabled = 1
    @user.save

    # Create a profile for user
    profile = Profile.new
    profile.image_uri = "https://i.stack.imgur.com/dr5qp.jpg"
    profile.user_id = @user.id
    profile.save

    UserMailer.welcome_email(@user).deliver_later(wait: 2.minutes)
    redirect_to(@user, :notice => 'User created')
    
    # flash[:success] = "Welcome to GNV Xplorer"
    redirect_to new_place_path

  end

  def show
    before_action :require_user, only: [:show]
    @user = User.find(params[:id])
    @users = User.all
  end

  def new
  end

  private
  def user_params
    params.require(:user).permit(:uname, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/event_comments_helper.rb
module EventCommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <body>
    <head>
      <title>GNV-Xplorer</title>
      <meta content="initial-scale=1, width=device-width" name="viewport">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag 'application', media: 'all' %>
      <%= javascript_include_tag 'application' %>
      <%= favicon_link_tag asset_path('y.png'), :rel => 'icon', :type =>  'image/png' %>

    </head>
  <div class="sticky-top">
    <header>
      <nav class="navbar navbar-expand-md bg-info">
        <%=link_to image_tag("GNV_new.png"), root_path, { :class=>"navbar-brand" } %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <% if current_user %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Places
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "Places", places_path, { :class=>"dropdown-item"} %>
                  <%= link_to "Add Place", new_place_path, { :class=>"dropdown-item"} %>
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Events
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "Events", events_path, { :class=>"dropdown-item"} %>
                  <%= link_to "Add Event", new_event_path, { :class=>"dropdown-item"} %>
                </div>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Places", places_path, { :class=>"nav-link"} %>
              </li>
              <li class="nav-item">
                <%= link_to "Events", events_path, { :class=>"nav-link"} %>
              </li>
            <% end %>

            <li class="nav-item">
              <%=link_to "Near Me", nearmes_path, { :class=>"nav-link"} %>
            </li>
            <% if current_user %>
              <li class="nav-item">
                <%=link_to "Logout", session_path(current_user.id), { method: :delete, class: "nav-link"} %>
              </li>
            <% end %>
          </ul>

          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline my-0 my-sm-0 text-muted" type="submit">
              <i class="material-icons">search</i>
            </button>
          </form>
          <ul class="navbar-nav nav justify-content-end">
            <% if current_user %>
              <li class="nav-item">
                <%= link_to current_user.uname, profiles_path, { :class=>"nav-link"} %>
              </li>
            <% else %>
              <li class="nav-item">
                <%=link_to "Login/Signup", sessions_path, { :class=>"nav-link"} %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>
    </header>

    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>">
        <%= message %>
      </div>
    <% end %>

    <div class="content">
      <%= yield %>
    </div>

    <footer class="footer">
      <div class="container">
        <div class="copyright float-right">
          &copy;
          <script>
            document.write(new Date().getFullYear())
          </script>, made with
          <i class="material-icons">favorite</i>
          by
          <a href="https://github.com/hosforddotme/y-team" target="_blank">Y Team</a>.
        </div>
      </div>
    </footer>

  </body>
</html>